name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🚧 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠️ Set up node and pnpm
        uses: volta-cli/action@v4

      - name: 🛠️ Cache dependencies
        uses: actions/cache
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 📝 Lint
        run: pnpm lint

      - name: 🧪 Run tests
        run: pnpm test:ci
